import { Sparkles, TrendingUp, ShieldCheck, Target, Zap, BarChart3 } from 'lucide-react';

const BestPropCard = ({ recommendedProp }) => {
  if (!recommendedProp) return null;
  const opponent = recommendedProp.opponent ? ` vs ${recommendedProp.opponent}` : '';
  
  // Determine EV badge color
  const getEVColor = (ev) => {
    if (ev > 5) return 'bg-green-500/20 text-green-400 border-green-500/30';
    if (ev > 3) return 'bg-emerald-500/20 text-emerald-400 border-emerald-500/30';
    if (ev > 1) return 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30';
    return 'bg-orange-500/20 text-orange-400 border-orange-500/30';
  };
  
  // Determine confidence color
  const getConfidenceColor = (score) => {
    if (score >= 70) return 'bg-sports-accent/20 text-sports-accent';
    if (score >= 50) return 'bg-yellow-500/20 text-yellow-400';
    return 'bg-red-500/20 text-red-400';
  };

  return (
    <div className="relative overflow-hidden bg-gradient-to-br from-sports-dark via-sports-card to-sports-dark border border-sports-accent/40 rounded-2xl p-6 shadow-[0_0_30px_rgba(29,241,106,0.15)] mb-8">
      {/* Decorative background elements */}
      <div className="absolute top-0 right-0 w-64 h-64 bg-sports-accent/10 rounded-full blur-3xl -mr-20 -mt-20 pointer-events-none"></div>
      
      <div className="relative z-10">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2 bg-sports-accent/20 text-sports-accent px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider">
            <Sparkles size={14} />
            <span>Best Prop Today</span>
          </div>
          <div className="text-sports-muted text-xs font-medium">Auto-generated by AI</div>
        </div>

        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
          <div className="flex-1">
            <div className="flex items-center gap-2 mb-1">
              <h2 className="text-3xl md:text-5xl font-black text-white tracking-tighter">
                {recommendedProp.player}
              </h2>
              <span className={`text-[10px] font-black px-2 py-0.5 rounded uppercase mt-2 ${
                recommendedProp.category === 'High Edge' ? 'bg-sports-accent text-sports-dark shadow-[0_0_10px_rgba(29,241,106,0.5)]' : 
                recommendedProp.category === 'Medium Edge' ? 'bg-sports-highlight text-white shadow-[0_0_10px_rgba(168,85,247,0.5)]' : 'bg-yellow-500 text-sports-dark'
              }`}>
                {recommendedProp.category || 'High Edge'}
              </span>
            </div>
            <div className="text-xl md:text-2xl font-bold text-sports-accent flex items-center gap-2 opacity-90 mb-4">
              <TrendingUp size={24} className="animate-bounce" />
              {recommendedProp.prop}
            </div>

            {/* Confidence Factors Breakdown */}
            <div className="flex flex-wrap gap-2 mt-2">
              {recommendedProp.factors?.map((factor, i) => (
                <span key={i} className="text-[9px] font-bold text-sports-muted bg-sports-secondary/40 border border-sports-secondary/50 px-2 py-1 rounded-md uppercase tracking-widest">
                  {factor}
                </span>
              ))}
            </div>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            <div className="bg-sports-dark/60 backdrop-blur-md border border-sports-secondary/50 rounded-2xl p-4 flex flex-col items-center justify-center min-w-[95px] hover:border-sports-accent/40 transition-colors">
              <span className="text-[9px] text-sports-muted font-black uppercase tracking-widest mb-1.5 opacity-70">Probability</span>
              <span className="text-2xl font-black text-white text-glow-accent">{recommendedProp.probability}%</span>
            </div>
            
            <div className="bg-sports-dark/60 backdrop-blur-md border border-sports-secondary/50 rounded-2xl p-4 flex flex-col items-center justify-center min-w-[95px] hover:border-sports-accent/40 transition-colors">
              <span className="text-[9px] text-sports-muted font-black uppercase tracking-widest mb-1.5 opacity-70">Simulation</span>
              <span className="text-2xl font-black text-sports-accent text-glow-accent">
                {recommendedProp.monteCarlo != null ? `${recommendedProp.monteCarlo}%` : `${recommendedProp.probability}%`}
              </span>
            </div>

            {/* NEW: EV Badge */}
            <div className={`backdrop-blur-md border rounded-2xl p-4 flex flex-col items-center justify-center min-w-[95px] hover:border-opacity-60 transition-colors ${getEVColor(recommendedProp.ev_percentage)}`}>
              <span className="text-[9px] font-black uppercase tracking-widest mb-1.5 opacity-80 flex items-center gap-1">
                <Zap size={10} /> EV
              </span>
              <span className="text-xl font-black">{recommendedProp.ev_percentage > 0 ? '+' : ''}{recommendedProp.ev_percentage}%</span>
            </div>

            {/* NEW: Minutes Projection (Critical Info) */}
            <div className="bg-sports-dark/60 backdrop-blur-md border border-blue-500/30 rounded-2xl p-4 flex flex-col items-center justify-center min-w-[95px] hover:border-blue-500/50 transition-colors">
              <span className="text-[9px] text-blue-400 font-black uppercase tracking-widest mb-1.5 opacity-80 flex items-center gap-1">
                ⏱️ Minutes
              </span>
              <span className="text-2xl font-black text-blue-300">{recommendedProp.projected_minutes}m</span>
              <span className="text-[8px] text-blue-300 mt-1">{recommendedProp.minutes_confidence}</span>
            </div>

            {/* NEW: Confidence Score with progress bar */}
            <div className={`backdrop-blur-md border rounded-2xl p-4 flex flex-col items-center justify-center min-w-[95px] ${getConfidenceColor(recommendedProp.confidence_score)}`}>
              <span className="text-[9px] font-black uppercase tracking-widest mb-2 opacity-80">Confidence</span>
              <span className="text-2xl font-black">{recommendedProp.confidence_score}%</span>
              <div className="w-full h-1.5 bg-gray-700 rounded-full mt-2 overflow-hidden">
                <div 
                  className={`h-full transition-all ${recommendedProp.confidence_score >= 70 ? 'bg-sports-accent' : recommendedProp.confidence_score >= 50 ? 'bg-yellow-400' : 'bg-red-400'}`}
                  style={{width: `${recommendedProp.confidence_score}%`}}
                />
              </div>
            </div>

            {/* NEW: Kelly Criterion Units */}
            <div className="bg-sports-dark/60 backdrop-blur-md border border-sports-secondary/50 rounded-2xl p-4 flex flex-col items-center justify-center min-w-[95px] hover:border-sports-accent/40 transition-colors">
              <span className="text-[9px] text-sports-muted font-black uppercase tracking-widest mb-1.5 opacity-70 flex items-center gap-1">
                <BarChart3 size={10} /> Kelly
              </span>
              <span className="text-lg font-black text-sports-accent">{(recommendedProp.kelly_fraction_quarter * 100).toFixed(2)}%</span>
              <span className="text-[8px] text-sports-muted mt-1">{recommendedProp.recommended_units}u</span>
            </div>

            <div className="bg-sports-accent/10 backdrop-blur-md border border-sports-accent/30 rounded-2xl p-4 flex flex-col items-center justify-center min-w-[95px] shadow-[0_0_20px_rgba(29,241,106,0.1)]">
              <span className="text-[9px] text-sports-accent font-black uppercase tracking-widest mb-1.5 flex items-center gap-1 text-glow-accent">
                Edge {recommendedProp.edge} <ShieldCheck size={10} />
              </span>
              <span className="text-lg font-black text-white uppercase tracking-tighter">{recommendedProp.confidence_rating || recommendedProp.confidence}</span>
            </div>
          </div>
        </div>

        {/* NEW: Explanation/Reasoning Section */}
        {recommendedProp.explanation && (
        <div className="mt-6 bg-sports-dark/40 border border-sports-secondary/30 rounded-xl p-4">
          <p className="text-xs font-bold text-sports-accent uppercase tracking-widest mb-3 flex items-center gap-2">
            💡 Why This Pick?
          </p>
          <div className="text-xs text-sports-muted leading-relaxed font-medium whitespace-pre-wrap">
            {recommendedProp.explanation.split('\n').map((line, i) => (
              <div key={i} className="mb-1">{line}</div>
            ))}
          </div>
        </div>
        )}
      </div>
    </div>
  );
};

export default BestPropCard;
